<html>
<head></head>
<body>
<h1>{!! $title !!}</h1>
<div>

  <table class="table">
      <tbody>
          <tr>
            <th align="left">Name</th>
              <td>{!! $content->make->name !!}</td>
          </tr>
          <tr>
            <th align="left">Color</th>
              <td>{!! $content->color->name !!}</td>
          </tr>
          <tr>
            <th align="left">Model</th>
              <td>{!! $content->model !!}</td>
          </tr>
          <tr>
            <th>Type</th>
              <td>{!! $content->type !!}</td>
          </tr>
          <tr>
            <th>Year</th>
              <td>{!! $content->year !!}</td>
          </tr>
          <tr>
            <th>Engine Capacity</th>
              <td>{!! $content->engine_capacity !!}</td>
          </tr>
          <tr>
            <th>Transmission</th>
              <td>{!! $content->transmission !!}</td>
          </tr>
          <tr>
            <th>Milenage</th>
              <td>{!! $content->mileage !!}</td>
          </tr>
          <tr>
            <th>Price</th>
              <td>{!! $content->price !!}</td>
          </tr>
      </tbody>
  </table>
</div>
<p>&nbsp;</p>
<p><i>This is an autogenerated email. For any immediate queries, please contact us on 313 8080.<i></p>
<p>Thanks</p>
<p><b>SuperCars Team</b></p>
</body>
</html>
