<html>
<head></head>
<body>
<h1>{!! $title !!}</h1>
<h2>{!! $content->name !!}</h2>
<div>
    <!-- Car Make -->

  <p> this is an example of a vertical table </p>
  <table class="table">
      <tbody>
          <tr>
            <th>Row</th>
              <td>1</td>
              <td>2</td>
              <td>3</td>
          </tr>
          <tr>
            <th>First Name</th>
              <td>John</td>
              <td>Peter</td>
              <td>John</td>
          </tr>
          <tr>
            <th>Last Name</th>
              <td>Carter</td>
              <td>Parker</td>
              <td>Rambo</td>
          </tr>
        <tr>
            <th>Email</th>
              <td>johncarter@mail.com</td>
              <td>peterparker@mail.com</td>
              <td>johnrambo@mail.com</td>
          </tr>
      </tbody>
  </table>
</div>
<p>&nbsp;</p>
<p><i>This is an autogenerated email. For any immediate queries, please contact us on 313 8080.<i></p>
<p>Thanks</p>
<p><b>SuperCars Team</b></p>
</body>
</html>
